bin/9l

make 9l accept Linux kernel version 4.x

---

bin/mount
src/cmd/9pfuse/fuse.c

macports installs osxfuse under /opt/local

mount and 9pfuse: detects macports installed osxfuse

---

lib/keyboard

Change-Id: Ice1c8c9d15cc6febf32dc2b7c449d457acc319b6

keyboard: add compose sequences lc and rc for ceiling brackets

---

src/cmd/devdraw/x11-init.c

As described here:
https://plan9port-review.googlesource.com/c/plan9/+/1470

Set displaydpi on devdraw x11 attach 

---

.travis.yml
src/cmd/devdraw/cocoa-screen-metal.m

You are going to hate this.
However, this one line fixes #207 #208 #214.

devdraw: cocoa metal screen uses a dirty hack to make everything smooth

---

src/cmd/mk/archive.c

Updates #313
Change-Id: I0e27e15feacb77391bc1decee7cf720d64d14586

mk: fix out of bounds access

---

src/cmd/tar.c

tar: remove /bin/ when invoking decompressors

---

src/cmd/rio/winwatch.c

This is new code, and custom to plan9port.  Make it
conform more closely to plan9 style.

winwatch: Plan 9-ify.

---

dist/deb.html
dist/main.html
dist/pkg/main
dist/unix.html
install.txt
man/man1/0intro.1
unix/NOTICE.bio
unix/NOTICE.fmt
unix/NOTICE.mk
unix/NOTICE.regexp
unix/NOTICE.utf

Fix broken references to plan9.bell-labs.com/plan9

---

bin/9c
bin/9l

Step 1 to getting everything working with macOS on Apple's new chips. INSTALL completes successfully with just these changes, although more work needs to be done overall.

9c, 9l: updates for macOS arm64.

---

src/cmd/9p.c

Here is an excerpt from 9p(1) (emphasis mine)
> repeat until end-of-file on standard input: copy a **line** from the
> file to  standard output,  copy a *line* from standard input to the
> file. Print errors, but don't give up. Rdwr is useful for interacting
> with servers like factotum(4).
Here is a simple shell pipeline that you would think, based on the
description above, would be sufficient to fetch a `proto=pass` key
from factotum:
% 9p rdwr factotum/rpc <<EOF | awk '/^ok/ && NF > 1'
start proto=pass role=client service=imap server=imap.example.com user=foo@example.com
read
EOF
However, this does not work. The `rdwr` subcommand's main loop assumes
that `read()` will read a single line, no more, no less. From a shell
script it is difficult to control when and how much output is …

9p: parse lines in rdwr command

---

bin/9c
bin/9l
src/cmd/9term/AIX.c
src/cmd/9term/bsdpty.c
src/libdraw/string.c

This fix resolves the devdraw hang issue on AIX.

libdraw: Fix GUI programs on AIX

---

man/man3/stat.3

man/man3/stat.3: Update man page to match include/libc.h

---

src/cmd/acme/cols.c

acme: fix incorrect border height after grow

---

src/cmd/acme/acme.c

acme: don't let button&modbutton images overwrite tag/body border

---

src/cmd/devdraw/x11-screen.c

Certain XkbOptions in X11 would change keysyms for modifier keys
between the key press and key release.
For example, under the XkbOptions "grp:shifts_toggle", though shift
keys remain Shift_L/R when pressed, they become ISO_Group_Next/Prev
when released.
This behavior makes devdraw unable to detect the release event
correctly and as a result mouse button 1 click always interpreted
as button 3 event after a shift key is used.

devdraw/x11: fix modifier key handling for some XkbOptions

---

src/cmd/fontsrv/main.c

fontsrv: always compute new height and ascent for the font file

---

include/u.h

Added a paren to fix a warning in u.h

---

src/cmd/plumb/rules.c

When processing plumber rule definitions, each time a string
expansion is performed in `expand()`, throw one of the following
two errros before returning in case:
• the output buffer is exhausted before the end of input, or
• the input expression is exhausted while a quoted string literal
is being consumed.
Fixes #568, fixes #569.

plumber: fail on buffer exhaustion or runaway quotes in string expansion

---

README.md

README.md: Drop travis-ci badge

---

bin/B

B's usage message redirects its stderr to stdout instead of vice versa. Fix this.

B: Print usage message to stderr
