- .travis.yml
The first commit adds the Travis CI configuration and the second commit adds the Coverity Scan addon to the Travis CI configuration.
This PR is also a way to experiment how we work with PRs.
> Add Travis CI and Coverity Scan support

- src/cmd/rc/unixcrap.c
rc on amd64 stores ulimit values as 32-bit int, but the limits on
OpenBSD amd64 can exceed 2^31, so "ulimit -a" shows some values as
negative. This is a problem when I want to increase my ulimit but
the hard ulimit values are printed as negative.
> Use proper type for storing ulimit values.

- src/cmd/auxstats/FreeBSD.c
as the old grody way doesn't work any more on FreeBSD-10 and later.
> Get network stats in a portable manner on FreeBSD

- src/cmd/9pfuse/fuse.c
read(3) sometimes errors with EINTR on macOS over slow connections.
9pfuse(1) now retries read(3) instead of sysfatal(3)ing.
> 9pfuse: retries read(3) upon EINTR

- src/cmd/9term/rcstart.c
TERM_PROGRAM is the customary way to identify which kind of terminal
emulator program one uses on macOS.
This change sets TERM_PROGRAM to termprog since both variables are used
for the same purpose.
For some examples, see:
https://apple.stackexchange.com/questions/42714/what-is-the-term-program-and-term-program-version-environment-variables-used-fo
https://github.com/jwilm/alacritty/issues/781
https://github.com/justinmk/vim-gtfo/issues/3
https://github.com/neovim/neovim/blob/f050aaabbb31b58ebac519a6f7014610f2b119f0/src/nvim/tui/tui.c#L206-L211
> cmd/9term: Set TERM_PROGRAM to termprog

- src/cmd/fontsrv/osx.c
Double the width returned by CTFontGetBoundingBox when drawing
Add box drawing characters for determining the line height
freememimage(1) for the character memimage
It should fix #146 #120, and likely #18.
> fontsrv: enlarge drawing buffer for subfonts on macOS

- src/cmd/upas/nfs/imap.c
According to RFC 3501 the arguments to the LOGIN command should be quoted strings (or length prefixed string literals). Without quoting, authentication to some IMAP servers (e.g. Dovecot) will fail.
> Correctly quote IMAP LOGIN command arguments

- src/cmd/fontsrv/x11.c
* Avoid allocating empty images by adding 1 to width/height. This was
crashing fontsrv. The total width of the subfont image can be zero
even if the characters are present in the font. For example, all the
characters in x0300.bit (part of "Combining Diacritical Marks" Unicode
block) have zero width.
* Enable all Unicode ranges. We need to enable U+0000, otherwise libdraw
complains with: "stringwidth: bad character set for rune 0x0000 in ..."
* Use the same fallback glyph (pjw face) as OS X. This also fixes a bug
where advance was set to the total width of subfont instead of the
character.
Update #125 (most likely fixes the crash if in X11)
CC @paulzhol
> fontsrv: copy some fixes from OS X to X11

- src/cmd/9term/FreeBSD.c
Opening /dev/ptyXX files fails on recent
FreeBSD versions.
Following the same fix being applied to
Linux, OpenBSD, and Darwin, we use openpty
to open a pseudoterminal in openpts.
> 9term: fix getpts on FreeBSD 11.2

- src/cmd/fontsrv/mkfile
- src/cmd/fontsrv/osx.c
macOS Mojave version 10.14 starts to disable font smoothing.
We disable font smoothing for OSX_VERSION >= 101400 to match the
system default font rendering.
It also makes the font rendering on macOS similar to that on X11.
> fontsrv: disable font smoothing on osx

- src/cmd/acme/cols.c
To reproduce, create a column with at least two windows and resize
acme to have almost zero height.
> acme: avoid division by zero when resizing col

- src/cmd/fontsrv/x11.c
This makes fontsrv use the PostScript font names on X11.
The PostScript font names contains only alphanumeric and
hyphens.  This allows us to use the Font command in acme.
It also matches the font names used by fontsrv on macOS,
which has been using PostScript font names.
Note: this patch changes font names for X11 users.
Those who uses X11 need to remove the spaces from the font names in their profile or acme.dump.
> fontsrv: x11 uses FC_POSTSCRIPT_NAME

- src/cmd/devdraw/cocoa-screen.m
This makes 2-1 chords possible with touchpad on a mac laptop.
> make ctrl generate 1-click while mouse down

- plumb/basic
Fixes #122, #140.
As reported in #122, `file:1:1` moves to the end of the file,
and `file:1:2` fails with “address out of range”.
I’ll use file:2:3 as an example so we can tell the line and column number apart.
What’s happening is this:
plumb/basic matches `2:3` using twocolonaddr (from plumb/fileaddr),
then sets addr to `2-#1+#3`
(the 1 is constant and was introduced because column numbers are 1-based).
Acme interprets this in three steps:
1. find the range (q0, q1) that contains line 2
2. create the range (q2, q2) where q2 = q0 - 1
3. create the range (q3, q3) where q3 = q2 + 3
The second step has a branch where if q0 == 0 and 1 > 0
(remember that 1 is constant and comes form plumb/basic),
q0 is set to the end of the file.
This makes addressing things at the end of the file easier.
The …
> plumb/basic: Move forward first so we don't wrap around

- mac/9term.app/Contents/MacOS/9term
9term set *$PLAN9* if *$PLAN9* is not set. But *$PATH* is not set.
As a result, 9term exits with errors: 
> /usr/local/plan9/bin/9term: exec devdraw: No such file or directory
> /usr/local/plan9/bin/9term: initdraw: muxrpc: unexpected eof
> 9term.app: add $PLAN9/bin to $PATH if not already in $PATH

- src/cmd/fontsrv/x11.c
The comparison between the patched and current versions can be seem in the images below (left is gnome-terminal, right is 9term):
**Current**
**Patched**
> fontsrv: increase x11 font height scale

- unix/mkfile
Was playing around and attempted mk tgz in plan9front/unix and it failed (create a '-' tar archive). Per tar man file, this version of tar should use tar c <name> to generate an archive from standard out.
This is just a simple patch to make that change.
> Fixing tar options for mkfile in unix directory

- unix/mkfile
Use the widely accepted /dev/stdout.
> unix: fix for tar on FreeBSD

- INSTALL
FreeBSD 11.2 by default does not have gcc.
> INSTALL: use cc to check for fontsrv on non-Darwin

- src/cmd/devdraw/cocoa-screen-metal.m
Fixes bug where devdraw does not "notice" mouse position after task
switch. Fixes https://github.com/9fans/plan9port/issues/232.
In Acme, which uses "focus follows mouse", this bug is particularly annoying. The effect is that I often have to wiggle my mouse (or touch the trackpad) after switching back to Acme with Cmd-Tab.
> devdraw: respond to windowDidBecomeKey on darwin

- src/cmd/devdraw/cocoa-screen-metal.m
It is possible to receive multiple screen resize events, and resizeimg
would be called for different sizes, before _flushmemscreen actually
gets called with rectangle sizes different from the most recent
resizeimg call.  The size mismatch would trigger illegal memory
access inside _flushmemscreen.
This commit protects _flushmemscreen by returning early if the requested
rectangle is outside of the current texture rectangle.
fixes #221
> devdraw: cocoa metal returns early in _flushmemscreen for wrong rectangles

- src/cmd/acme/xfid.c
After acme receives a `menu` or `nomenu` control event, it doesn’t update the tag.
Since these events potentially modify the tag (Undo, Redo and Put are only automatically included if `menu` is active), it should.
> acme: Update tag after receiving menu/nomenu control event

- src/cmd/devdraw/cocoa-screen-metal.m
hi, apologies in advance for how rough this might be: I noticed that acme was marked "Yes" in the "Requires High Perf GPU" column in macOS' Activity Monitor app on my dual-GPU macbook. Selecting a low-power integrated GPU seems to change this behavior, I'm unaware if there's a reason to use the default/high-performance GPU for devdraw.
> prefer integrated GPU for macOS metal rendering

- src/cmd/devdraw/cocoa-srv.c
- src/cmd/devdraw/x11-srv.c
- src/libdraw/drawclient.c
- src/libdraw/drawfcall.c
Some libraries that depend on devdraw don't know about
32x32 cursor -- mainly 9fans.net/go/draw.
> libdraw,devdraw: fix compatibility with old 16x16 cursor protocol

- src/cmd/devdraw/cocoa-screen-metal.m
> devdraw: macOS metal screen no longer translates ctrl-h

- src/cmd/samterm/main.c
Samterm should strict check non-typing character Kcmd to handling Mac IME marked range.
Without this patch illegal range deleted:
With this patch:
This change was included in my closed patch of support Mac IME #121 
But not included changes of #194, so I sent this again 😀 
And this patch also solves can't input Zenkaku alphabet character(e.g `ｈ`)  in sam.
> samterm: Strict check Kcmd non-typing character to handle Mac IME.

- src/cmd/devdraw/cocoa-screen-metal.m
The immediate display of the screen sometimes miss the update from
the CPU side memory.  No obvious synchronization mechanism is available.
In order to make sure the screen updates properly, we set needsDisplay
again after a minimal delay to ensure a second screen update.
Fix #268 for the time being and I will see if I can fix it properly.
> devdraw: cocoa metal screen adds a delayed update

- src/cmd/auxstats/Linux.c
According to <https://askubuntu.com/a/309146>, use of `/proc/acpi` to
get battery usage is deprecated. This commit replaces the two files from
this API with the single file `/sys/class/power_supply/BAT0/capacity`,
simultaneously removing the need to calculate battery percentage.
> auxstats: replace /proc ACPI calls with /sys ones

- src/cmd/plumb/rules.c
Instead of checking Fcall.data==nil, check Fcall.count==0.
The former check always fails after `gcc -O2` optimizations
(gcc version 8.3.0).
Also fix an out-of-bound read detected by valgrind:
```
==31162== Invalid read of size 1
==31162==    at 0x11005E: morerules (rules.c:739)
==31162==    by 0x110254: writerules (rules.c:775)
==31162==    by 0x10D2FE: fsyswrite (fsys.c:848)
==31162==    by 0x10C304: fsysproc (fsys.c:248)
==31162==    by 0x112E8C: threadstart (thread.c:96)
==31162==    by 0x4A682BF: ??? (in /usr/lib/libc-2.29.so)
==31162==  Address 0x4ea984a is 0 bytes after a block of size 250 alloc'd
==31162==    at 0x483AD7B: realloc (vg_replace_malloc.c:826)
==31162==    by 0x1196F3: p9realloc (malloc.c:53)
==31162==    by 0x10BDFD: erealloc (plumber.c:124)
==31162==    by 0x10FCD9: …
```
> plumber: fix EOF detection on writes to rules file

- src/cmd/upas/nfs/imap.c
When fetching, messages are sent to plumber as soon as the ENVELOPE part is read.
The date field of the message is sent when the INTERNALDATE part is read and
there is no guarantee that this will be read before the ENVELOPE.
This bug can be observed when using faces(1) which will retrieve messages with
a null date and then always display a 'Jan 1' date instead of the correct one.
The fix is to simply send the message to plumber after having read all parts,
thus ensuring the message is complete.
Fix issue #262
> upas/nfs: fix null date when message is sent to plumber

- src/cmd/hoc/hoc.y
The code had a nested use of the follow() function that could cause +=+
and -=- to register as ++ and --.  The first follow() to execute could
consume a character and match and then the second follow() could consume
another character and match.  For example i-=-10 would result in a syntax
error and i-=- would decrement i.
> hoc: don't nest calls to follow() when lexing ++/+= and --/-=

- bin/9l
I'm using a slightly non-head version on plan9port here, but I needed this change to compile and link programs.
I think the real credit for this change goes to W.F. Cody who documented it on this forum entry:
https://bbs.archlinux.org/viewtopic.php?pid=1119508#p1119508
> 9l: support Linux version 5.0+

- bin/9l
Per the discussion on issue #247: makes 9l correct for FreeBSD 12, and we won't have to revisit it until FreeBSD 20, modulo other changes.
> 9l: support FreeBSD ≥ 12 (fixes issue #247)

- src/cmd/awk/lib.c
awk was splitting records into bytes instead of runes for empty FS.
For example, this was printing only the first byte of the utf-8 encoding
of é:
echo é | awk 'BEGIN{FS=""}{print $1}'
The change just copies how the `split` function handles runes.
Originally reported by kris on twitter:
https://twitter.com/p9luv/status/1180436083433201665
> awk: split record into runes for empty FS

- man/man4/plumber.4
- src/cmd/plumb/fsys.c
- src/cmd/plumb/plumber.c
- src/cmd/plumb/plumber.h
In MacOS, services run by launchd must run in the foreground, since
launchd manages forking and other resources.
> plumber: add -f (foreground) option

- bin/9c
- bin/9l
NixOS sandboxed builds (at least on Mac) don't have access to /tmp,
and this should be better POSIX.
> 9c, 9l: use $TMPDIR if available

- src/cmd/page/cache.c
- src/cmd/page/ps.c
Page was hanging because ghostscript never closes the fd from which
we're reading BMP data. We close our end of the pipe so that ghostscript
will close its end.
Tested with ghostscript version 9.50.
Fixes #124
> page: fix hang for forward-only postscript files

- src/cmd/ed.c
Temp file size is now declared in an enum; changing it from the default introduces a subtle bug in `putline`, which expects 32767.
Mask with `NBLK-1` instead.
> ed: replace magic number usage (temp file size fix).

- src/cmd/page/pdfprolog.c
- src/cmd/page/pdfprolog.ps
Ghostscript 9.27 removed GS_PDF_ProcSet and pdfdict due to a security
issue (see https://security-tracker.debian.org/tracker/CVE-2019-3839).
This fix was contributed by @onyxperidot (see #279).
Fixes #279
> page: fix pdf prolog for ghostscript >= 9.27

- src/cmd/ed.c
Given that tabs are being used for comment alignment (compare `ESCFLG` which uses a single `\t` to `FNSIZE` which uses two), remove one of the tabs separating `NBLK` from its comment.
With this change, `enum` comments are aligned when tabs are rendered as 4 or 8 spaces. (With 2 or 6, they're already misaligned.)
Alternatively, spaces could be used here instead, though that would not be in keeping with the file's (venerable!) style.
> ed: formatting tweak (remove redundant tab).

- src/cmd/cb/cb.c
Just added a pair of parentheses. I also ran cb on cb.c to beautify the
code.
This is actually on Gerrit from 2016:
https://plan9port-review.googlesource.com/c/plan9/+/1574
Change-Id: I5e234adba0f95c13d6eecb121bf11bba4bf54566
> cb: fix a null pointer dereference

- src/cmd/acme/util.c
- src/cmd/acme/wind.c
The C standards disallow passing null pointers to memmove and memcmp.
Change-Id: I1c88c2adbc32a23ef742f206038b8f7c4e0540c7
> acme: do not pass null pointers where disallowed

- src/cmd/ls.c
Passing a null pointer to qsort is an error in C (GCC and Clang agree
with the standards there, so this is no joke).
Change-Id: Ia2b015793a75ea4e85ae8f47da6beead9c4290e6
> ls: check that pointer is not nil before calling qsort

- src/cmd/htmlroff/t2.c
This is actually from 2016:
https://plan9port-review.googlesource.com/c/plan9/+/1590
Change-Id: I6f2a3d71a9dd589eff7ab15b3c1d3997254b3c35
> cmd/htmlroff: fix buffer overflow in t2.c getqarg

- buildEnvironmentVariables
- dist/buildmk
- src/mkhdr
This should prevent the issues of dist/buildmk and src/mkhdr getting out
of synchronization yet again.
I also add a rule for arm64 to the OBJTYPE sed command.
Fixes #243
Fixes #320
Change-Id: I60f69a1f32b5ed5ae5ac8a1659c38e29debed005
> all: sync and dedup the creation of the SYSNAME and OBJTYPE env vars

- INSTALL
- bin/9c
- bin/9l
note that I can only be sure this will work at OpenBSD and DragonFly BSD, however it shouldn't fail at FreeBSD (it will fail, FreeBSD always fails me) and NetBSD (does plan9port build at NetBSD anyway?)
> INSTALL, 9c, 9l: improve handling of *BSD

- man/man1/9term.1
- src/cmd/9term/9term.c
- src/cmd/9term/dat.h
- src/cmd/9term/wind.c
Add a menu item which functions similar to acme's `Look` command.
This is copied from 9front. See:
https://code.9front.org/hg/plan9front/rev/1f1596dbca51
https://code.9front.org/hg/plan9front/rev/d2de1d2f7b48
> 9term: add a "look" menu item

- src/lib9/ctime.c
- src/libndb/sysdnsquery.c
GCC pointed this out with some "warning: ‘strncpy’ specified bound NUM
equals destination size [-Wstringop-truncation]" warnings.
Change-Id: Id8408b165f6e4ae82c96a77599d89f658d979b32
> lib9, libndb: exclude terminating null from strncpy bound

- bin/9c
POSIX does not support grouping in case item patterns.
Installing with a strict POSIX shell fails with:
/usr/local/plan9/bin/9c: line 82: syntax error near unexpected token `('
/usr/local/plan9/bin/9c: line 82: `*(DragonFly|BSD)*gcc*)	usegcc ;;'
This change expands the patterns to work around the limitation.
See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10
(and search for `case_clause`)
> 9c: Fix case patterns for DragonFly and other BSDs

- src/cmd/venti/srv/icache.c
This splits a certain vtmallocz call in mkihash into two vtmallocz
calls. The first issue this fixes is that the C aliasing rules were not
respected in the code before this commit. The other thing is that this
enables better memory alignment guarantees.
Updates #313
Change-Id: Ia4f3e0fc85facc778193f5e977d4f99a1a9abd23
> cmd/venti/srv: split memory allocation call

- man/man8/vbackup.8
- man/man8/venti.8
- src/cmd/venti/srv/printarena.c
This is just some minor modifications to one usage string and two man pages, correcting some inaccuracies that bit me when I installed a venti server.
> Make venti's doc more accurate

- src/cmd/fontsrv/x11.c
Some truetype fonts have good manual hinting.
Ignoring hinting makes the font render badly on low resolution screens.
This commit only disables the freetype autohinter, and allows hinting.
> fontsrv/x11: allow hinting and disable autohint only

- src/cmd/9pfuse/main.c
Without this change I was unable to run programs off 9pfuse, as the open would fail, because of "unexpected open flag 0100040". I later learned that 0100000 was actually cleared (O_LARGEFILE) and only 040 remained set. This seems to be the internal __FMODE_EXEC flag. I'm not sure that my approach (just clearing that flag) is correct, although it sure unblocks me. I noticed that v9fs seems to do a simpler translation of open modes from Unix to 9P, see /usr/local/src/linux/fs/9p/vfs_file.c:/uflags2omode/.
> cmd/9pfuse: ignore 0100040 open flag

- src/cmd/mk/symtab.c
syminit is only called once in main(), and at that point the global
array hash is still all zeroes, thus the call is a no-op; it gets
optimized out.
symdel and symstat also aren't used anywhere, so they are being removed.
The hash function was abstracted out of symlook and symdel, and changed
so as not to use signed integer overflow because that is forbidden in
standard C.
A version of this commit has actually been sitting on the p9p Gerrit
since 2016:
https://plan9port-review.googlesource.com/c/plan9/+/1572
Updates #313
Change-Id: I5478ae03f208a92a6ba16060486b946dcc4b2cf1
> mk: clean up symtab.c, fix hash

- src/cmd/devdraw/mac-screen.m
`window:willUseFullScreenPresentationOptions:` is an instance method
of the protocol `NSWindowDelegate`.
fix #333
> devdraw: correctly hides Mac menu bar

- bin/soelim
- lib/moveplan9.files
- man/man1/soelim.1
The troff `.so` preprocessor `soelim` is missing. It is essential for any troff workflow beyond individual manpages.
In Plan9 it was rewritten as an rc script (like man) and located in `/rc/bin.` It seems not have made the transition into plan9port.
This pull request (1) imports the Plan9 rc script into `bin/` and fixes the `#!` line to conform to plan9port expectations; (2) adds an entry into `lib/moveplan9.files` to trigger the `/usr/local/plan9` pathname relocation during `INSTALL;` and (3) imports the Plan9 `soelim.1` manpage with some light-touch fixes for plan9port style (mainly adding the `\*9` macro in the SOURCE section and removing hard-coded spacing requests).
The tears-of-frustration comments in the script are the original ones. I have left them untouched, as a mark of respect …
> troff: fix missing soelim

- src/cmd/draw/clock.c
`struct Tm tms` was set but never referenced; noticed
in a compiler warning.  Remove it.
> clock: Remove unused static variable in clock.c

- man/man1/compress.1
- man/man1/tar.1
- src/cmd/compress/compress.c
- src/cmd/compress/mkfile
Good old `compress` is missing. `tar` calls out to `compress` and `uncompress` when dealing with `.Z` archives and fails if it cannot find `compress` and `uncompress` installed.
This pull request (1) imports Plan9 `/sys/src/cmd/compress/compress.c;` (2) adds the `#define USED` voodoo needed for a successful build; (3) provides a plan9port-style mkfile to build `compress` and `uncompress` (and `zcat);` (4) scavenges the `compress.1` manpage from Research Unix, as it is missing from Plan9; (5) deletes the `(not distributed)` in reference to `compress` in the `tar(1)` manpage.
Not sure why compress was claimed not be distributed. The Plan9 ISO has a compress binary in I386/bin, and the source is where you would expect it to be as part of a full build. Only the manpage is missing. I guess it …
> compress: fix missing (un)compress

- src/cmd/rio/xshove.c
My use case for this is a script I have that makes windows visible after I moved from a large to a small screen (using Linux, rio).
> cmd/rio: xshove: set geometry by window id

- src/cmd/devdraw/mac-screen.m
and not quit an application unexpectedly
> devdraw: fix `cmd-r` to toggle retina vs. non-retina mode on macOS

- bin/9c
Version 10 of `gcc` enforces `-fno-common`, which breaks the build of a number of programs, which in turn forces the `INSTALL` script to fail.
This affects anyone moving to version 10 of `gcc`, which is now the default compiler on (at least) Fedora 32 (just released).
This fix reverts to the pre-10 behaviour by over-riding the (new) default with `-fcommon`.
The real fix is to clean up stray redefinitions which are intended to be declarations...
See [https://gcc.gnu.org/gcc-10/porting_to.html](url)
> 9c: fix for gcc version 10 new common redefinition behaviour

- src/lib9/fmt/fmt.c
atomics were added in GCC 4.9:  https://gcc.gnu.org/gcc-4.9/changes.html
Updates the fix to https://github.com/9fans/plan9port/issues/390
> fmt: adjust GCC version check

- src/cmd/fontsrv/x11.c
Hopefully this fixes the incorrect baseline of fonts in X11 described in #372. The number 1.35 was empirically determined in #111. There should be a better approach ...
> scale f->originity to match f->height

- src/cmd/devdraw/srv.c
- src/libdraw/drawclient.c
**getns()** returns a pointer to a malloced string. In some cases that malloced string was not freed causing memory leaks.
> devdraw, libdraw: fix memory leaks by freeing getns() malloced string

- src/cmd/touch.c
This fixes https://github.com/9fans/plan9port/issues/436
This doesn't necessarily address the underlying issue: calling p9create with
mode = OREAD should probably be allowed, but currently doesn't work on
OpenBSD.
> touch: fix for OpenBSD.

- lib/moveplan9.files
In 0bd14783426d137428ffae7cd89cfc06b88d1b11, `bin/wintext` became an rc executable. That means its shebang now needs to be rewritten by moveplan9.sh.
Without this, wintext is broken when plan9port is installed somewhere other than `/usr/local/plan9`.
> wintext: add to moveplan9.files

- src/cmd/eqn/e.h
- src/cmd/eqn/input.c
- src/cmd/htmlroff/roff.c
- src/cmd/xd.c
- src/libhtml/lex.c
There are a few more warnings I don't have time to look at.  Below are the remaining warnings.
```
>>> cd /home/xjin/pkg/p9p/src/libmach; mk all               
9c -I. machpower.c
machpower.c:223:34: warning: ‘i.rd’ may be used uninitialized in this function [-Wmaybe-uninitialized]
223 |   if (x.op == 24 && x.rs == x.ra && x.ra == i->rd) {
|       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
machpower.c:1188:8: note: ‘i.rd’ was declared here
1188 |  Instr i;
|        ^
>>> cd /home/xjin/pkg/p9p/src/libplumb; mk all
9c mesg.c
mesg.c:308:12: warning: ‘attr’ may be used uninitialized in this function [-Wmaybe-uninitialized]
308 |  m->attr = plumbunpackattr(attr);
|            ^~~~~~~~~~~~~~~~~~~~~
/home/xjin/pkg/p9p/include/libc.h:140:14: warning: ‘ntext’ may be used uninitialized in this …
```
> Fix a few out of bounds array access reported by gcc 10.2

- bin/mount
- src/cmd/9pfuse/fuse.c
[MacFUSE 4](https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.0.0) removes support for passing device fd to the mount command. Adds support for the receiving the fd over a socket instead, and updates command paths and filesystem name.
> 9pfuse: support MacFUSE >=4

- src/lib9pclient/read.c
Without this fix, fspread is trusting the server to return as much
data as requested, or less. If a server responds with more data
though, fspread writes beyond the bounds of the buffer to fill, which
is passed in by the caller. It depends on the caller of fspread()
where that buffer is, so there are various possible attack vectors.
In the Plan9 kernel, I found this implemented in devmnt.c, where
overly large responses are truncated to the size requested before
copying, so I assume that this strategy works here too.
This also affects fsread() and fsreadn(), which are based on
fspread().
> Fix buffer overflow in fspread().

- src/libthread/daemonize.c
This setpgrp breaks the build on FreeBSD (and I think all BSDs). This fix is tested on FreeBSD and macOS.
Pull request #471 already exists for this, but the fix isn't right. The correct fix is noted in the comments, but I'm not sure if there's a way to edit a pull request. This is a clean one to get the change in and the build working again.
> libthread: use setpgid instead of setpgrp

- src/lib9p/mkfile
commit 385a6d5877258cee0cac6151e6359c9206006b01 removed src/lib9p/_post.c
from the code base, but overlooked removing a reference to the
_post.o object file from the src/lib9p/mkfile.
This results in lib9p failing to compile:
* Running on Darwin...
* Compiler version:
Apple clang version 12.0.5 (clang-1205.0.22.11)
* Building mk...
* Building everything (be patient)...
>>> mk: don't know how to make '/Users/sasha/plan9port_fork/lib/lib9p.a(_post.o)' in /Users/sasha/plan9port_fork/src/lib9p
mk: for i in ...  : exit status=exit(1)
Remove _post.o from the list of dependent object files from
src/lib9p/mkfile to have lib9p compile.
Fixes: 385a6d587725 ("lib9p: Remove postmountsrv (#505)")
> lib9p: Fix compile error

- src/cmd/mk/shell.c
For cross-compiling plan9 from Unix, provide a way
to force `mk` to use `rc` instead of `sh` without
setting `MKSHELL` in individual `mkfile`s.
If the environment variable `FORCERCFORMK` is set,
`mk` will default to using `rc`, not `sh`.
Signed-off-by: Dan Cross <cross@gajendra.net>
> mk: provide a mechanism to default to `rc`

- src/cmd/rc/parse.c
kencc warns that this code is dead. Found while porting back to plan 9.
> rc: remove dead code.

- src/cmd/acme/cols.c
Don't move the mouse to a newly-created +Errors window if a mouse selection is in progress.
Fixes #19
> acme: Don't move the mouse if button depressed

- src/cmd/fontsrv/main.c
For fonts with subfiles that go beyond the xffff range, the font file size
calculation is incorrect, since lines beyond that range have additional
characters. This patch pads all of the ranges and subfont names with
leading zeros in order to keep them all lines the same length and fixes the
font file length calculation.
> src/cmd/fontsrv: pad subfile names to support correct file length

- src/cmd/deroff.c
Characters greater than 0X80 will cause a read beyond the bounds of the
array chars[].  For particular unicode characters this can cause deroff
to segfault.
A minimal example:
$ deroff
.EQ
u∈
Segmentation fault
Throughout deroff, charclass() is used instead of directly indexing
chars[] so I presume this was just missed.
> deroff: fix out-of-bounds access if runes above 0X80 are inside EQ clauses

- src/cmd/fossil/9proc.c
When the 9P connection is closed, reads on the connection will keep
returning 0. So, fossil ends up looping forever, trying to read a 9P
message, consuming 100% CPU. The fix interprets 0 bytes read as EOF.
Reproduce by killing the 9pserve process serving the fossil service, or
by listening on tcp and using 9p(1).
> fossil: fix EOF detection when reading 9P message

- src/libdraw/event.c
The function `startrpc()` stack allocates a local buffer of size 100:
```c
static Muxrpc*
startrpc(int type)
{
uchar buf[100];
^^^^^^^^
Wsysmsg w;
w.type = type;
convW2M(&w, buf, sizeof buf);
return muxrpcstart(display->mux, buf);
}
```
The function `convW2M()` is called passing `buf`. That function accesses
`buf` out-of-bounds:
```c
uint
convW2M(Wsysmsg *m, uchar *p, uint n)
{
...
case Tcursor2:
PUT(p+6, m->cursor.offset.x);
PUT(p+10, m->cursor.offset.y);
memmove(p+14, m->cursor.clr, sizeof m->cursor.clr);
memmove(p+46, m->cursor.set, sizeof m->cursor.set);
PUT(p+78, m->cursor2.offset.x);
PUT(p+82, m->cursor2.offset.y);
memmove(p+86, m->cursor2.clr, sizeof m->cursor2.clr);
memmove(p+214, m->cursor2.set, sizeof m->cursor2.set);
p[342] = m->arrowcursor;
^^^^^^
```
To fix the issue the size …
> libdraw: fix out-of-bounds access to local buffer in event.c:startrpc()

- src/cmd/auth/factotum/apop.c
It leaks that an allocated memory by *convreadm* when the response is not started with **"bad "**.
> factotum: plug a memory leak in apop

- INSTALL
- lib/moveplan9.sh
- src/cmd/sam/sam.c
- src/cmd/upas/nfs/imap.c
- src/cmd/upas/nfs/mkfile
- src/lib9/get9root.c
- src/lib9/mkfile
- src/mkmk.sh
I maintain a plan9port package for [Alpine Linux](https://alpinelinux.org). For this package, plan9port is installed to `/usr/lib/plan9` not `/usr/local/plan9` in order to comply with our packaging policy. Doing so is supported by plan9port via the `PLAN9_TARGET` environment variable and the `./INSTALL` -r flag. The installation script replaces hardcoded references to `/usr/local/plan9` with `PLAN9_TARGET` in various files via the `./lib/moveplan9.sh` script.
A few days ago I was [made aware](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/26969) that moveplan9.sh does not replace hardcoded references to `/usr/local/plan9` in C source code files since it is invoked after the code has been compiled. The following files have been identified to contain such hardcoded paths:
1. …
> Don't hardcode /usr/local/plan9 in C source code

- src/cmd/rio/manage.c
Screen was being queried from within a client after it had been free'd.
> rio: Fixed a use after free

- src/cmd/troff/n1.c
In groff, Heirloom Doctools troff, and neatroff, the `\~` escape
sequence produces an adjustable (paddable) but unbreakable space.
mandoc, which does not perform adjustment or render to typesetters,
supports the escape sequence as a synonym for `\ `, the same as `\0`.
This extension is of long pedigree: groff has supported it for at least
30 years, Heirloom for 17, mandoc for 13, and neatroff for 6.
Do the same as mandoc to prevent mis-rendering of documents using this
escape sequence.  Heirloom Doctools troff, a descendant of Documenter's
Workbench troff, would be a good place to look for a compatible
implementation of the adjustable semantics for this sequence.
> troff: support `\~` as an alias for `\ `

- man/man7/font.7
The word 'Oriental' is considered very outdated now.
> Modernise terminology

- lib/moveplan9.files
Seemingly the last use of a hardcoded /usr/local/plan9 path.
> add macedit to moveplan9.files

- src/cmd/cmp.c
- src/cmd/getflags.c
All utilities print their usage message to stderr,
cmp(1) and getflags(8) should do the same.
> src/cmd: print all usage messages to stderr

- bin/web
Default builds of Firefox remove the previous X remote interface,
now causing the use of -remote to silently exit and do nothing.
https://hg.mozilla.org/mozilla-central/rev/ef22d8cbf4ef
> web: fix plumbing with Firefox

- src/cmd/plumb/match.c
> plumber: set match variables past the first non-matching subexpression

- src/cmd/plumb/rules.c
> plumber: allow underscores in variable names in plumbing rules

- src/cmd/acme/xfid.c
As it is allowed to use spaces in file names set interactively through
the tag since 7b1c85f, do not reject names with spaces in the 'name'
ctl message either.
Fixes #559.
> acme: accept paths with spaces in the 'name' ctl message

- src/cmd/auth/factotum/dat.h
- src/cmd/auth/factotum/fs.c
- src/cmd/auth/factotum/log.c
When log reading exits, inuse flag should be cleared.
Signed-off-by: Tw <wei.tan@intel.com>
> factotum: fix log read inuse bug

- src/cmd/acme/wind.c
closes #10 
Title is self explanitory, fixes the age-old bug.
> acme/wind.c: redraw window body with bg color if too small for a single line

- src/cmd/rio/winwatch.c
A double free bug caused winwatch to crash sometimes upon closing a window.
The setjmp in the X error handler was not necessary.
The many XFlush and XSync calls, together with the surrounding changes of X error handler, were not necessary.
> winwatch: fix double free bug, simplify error handling, reduce X11 calls

- src/cmd/devdraw/mac-screen.m
Fix an issue with mouse wheel scrolling where float delta values were getting truncated into an integer, resulting in slow single-tick wheel scrolls being ignored
> devdraw: Fix mouse wheel scrolling in 1-tick increments on macOS

- src/cmd/plumb/match.c
- src/cmd/plumb/plumber.h
- src/cmd/plumb/rules.c
Motivated by #565.
Unlike, e.g., backslash references in replacement strings of sam’s
substitution command, where multi-digit subexpression references
would be ambigiuos, this change does not create any ambiguity that
cannot be easily avoided thanks to the single-quote literal syntax.
Granted, it is backward incompatible, but I doubt anyone wrote
something like `…$7123…` instead of `…$7'123'…`—for an eye used
to rc variable substitution syntax (which plumbing rules deliberately
resemble), the former is too uncomfortable looking, even if one knows
that in plumbing rules it works slightly differently than in rc.
In `subexpmatch()`, we consume all the digits following the dollar
sign even if the resulting number would exceed `NMATCHSUBEXP`
(or even overflow) to avoid any potential ambiguity …
> plumber: allow up to libregexp's NSUBEXP subexpression match variables

- include/regexp9.h
The most straightforward way to fix #565 in regards to point 3. Please let me know if 128 is not a good candidate for this bound, or if dynamic allocation would be preferable instead (as discussed in the linked issue).
> libregexp: allow up to 128 character classes in one regexp

- src/cmd/plumb/plumber.h
Thus up to two-digit subexpression match variables are supported (`$1` through `$99`) in addition to the entire expression match (`$0`).
The most straightforward way to fix #565 in regards to point 2.
**Depends on #609 being merged first!**
> plumber: increase NMATCHSUBEXP up to 100

- src/libregexp/regcomp.h
128 counting with the entire expression match (`$0`).
The most straightforward way to address point 2 from #565 (in preparation for #610). Please let me know if 128 is not a good candidate for this bound, or if dynamic allocation would be preferable instead (as discussed in the linked issue).
> libregexp: allow up to 127 captured subexpressions in one regexp

- src/libframe/frinit.c
Previously the vertical bar in tick was always black; fine if you use the standard black-on-white for everything, but any attempt to add a dark mode ran into trouble with the tick being half hard-coded black, half the new text color.
Using this new color matches the code around it.
> libframe: Match the color of tick

- src/cmd/acme/rows.c
Instead of only saving a window's currently displayed font's name (`t->reffont->f->name`) to the dump file (the current implementation), have Acme's Dump command save that window's combined low DPI and high DPI font names (`t->reffont->f->lodpi->name` and `t->reffont->f->hidpi->name`) when both are available.
This patch enables Acme dumps to better retain window font state.
In particular, it addresses the following font display quirk when using `Dump` and `Load` in Acme on high-DPI screens (200 DPI or more, like macOS Retina screens) without this patch, shown as an example:
1. Suppose we are using Acme on a high DPI screen, say a Retina MacBook screen.
2. Open a non-empty text file, say `/tmp/abc.txt`, in Acme on a high DPI screen type.
3. Execute `Font /mnt/font/AndaleMono/15a/font`. …
> acme: have Dump save both low and high DPI fontnames

- bin/9c
- bin/9l
Ever since the update of Xcode tools to version 15.1.0 in macOS 14.2, `ld` started to warn every time the same library is given more than once in its arguments. Since `-l9`, `-lsec`, `-lthread` frequently reoccur in Plan 9 Port linker invocations, this new behavior fills the `INSTALL` output with this useless warning.
Add it to the ignore list that is used to filter out the linker output. While at it, make the mechanics of warning-silencing in `9l` uniform with `9c` (and make quoting of variable substitutions a bit more consistent in both, along the way).
> 9l: silence the 'ignoring duplicate libraries' warning on macOS

- man/man4/ramfs.4
- src/cmd/ramfs.c
@dancrossnyc 
with modified erealloc(), ramfs works for me(tm).
Other changes:
Maxsize wasn't limiting ramfs memorty usage but per file usage.
-u added back from 4e. Man page amended.
4e man page for reference:
https://9p.io/magic/man2html/4/ramfs
> ramfs starts

- man/man4/mntgen.4
- src/cmd/mntgen.c
@dancrossnyc ptal
new file:   man/man4/mntgen.4
new file:   src/cmd/mntgen.c
I've been using mntgen(4) on linux for a year without issues.
> add mntgen(4) from plan9

- bin/man
- tmac/tmac.an
This tells bin/man to set the register L to very high to avoid pagination and updates tmac/tmac.an to use that value, if it's set, to set the page length. This is per Plan 9's rc/bin/man and sys/lib/tmac/tmac.an.
> man: don't paginate when using nroff

- dist/main.html
According to web.archive.org this link is dead since 2012/2013. According to original issue (http://codereview.appspot.com/4251044) that translation could be a machine translation.
> dist/main.html: remove dead link to Belorussian translation

- .gitignore
#637 introduced a new binary, but did not add it to `.gitignore`.
> .gitignore: add bin/mntgen

- src/cmd/devdraw/x11-screen.c
This bug is an intermittent annoyance and does not seem likely to be fixed soon. It means that every so often my acme becomes unusable because it behaves as if a mouse button is permanently set.
Avoid that issue by keeping track of mouse button state directly.
While we're about it, fix another annoying issue: under Linux the FocusOut event reset the kstate field but not the kbuttons field, meaning that the buttons state could inappropriately persist. This happened occasionally by accident, but was easy to reproduce: with the mouse button held down, drag outside the window and click Alt-Tab to switch away from the window. We see a KeyDown event followed by FocusOut but no KeyUp event.
Change-Id: I3708316478c80c41806d7157ae9929c6cd84b662
> cmd/devdraw: avoid use of X button state field

- bin/9c
- include/u.h
add -std=c17 to fix build failures on gcc 15 with c23 by default
for u.h i had to `#define __USE_POSIX 1` because `sigjmp_buf` is defined under an `#ifdef __USE_POSIX` in glibc, see https://github.com/bminor/glibc/blob/3473526758532d7356be80c7950e476e235b5fb2/setjmp/setjmp.h#L70
> Fix #716: Will not build on gcc 15
